name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:

  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry run ./scripts/precommit.sh
      - run: poetry run pytest -ra --timeout=60 --timeout_method=signal --durations=0 --cov=gistapi tests/*unit* tests/*it*
